# Generated by Django 6.0.5 on 2026-05-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirportLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iata_code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("sub_category", models.CharField(max_length=100)),
                ("scope", models.IntegerField()),
                ("factor_value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("year", models.IntegerField(default=2026)),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.IntegerField()),
                ("category", models.CharField(max_length=50)),
                ("activity_date", models.DateField()),
                (
                    "original_quantity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "original_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("normalized_quantity", models.FloatField(blank=True, null=True)),
                (
                    "normalized_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("calculated_emissions", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved & Locked"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged with Anomaly"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("validation_flags", models.JSONField(blank=True, default=list)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlantLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("grid_region", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_by",
                    models.CharField(default="System Analyst", max_length=100),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "normalized_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="api.normalizedrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="normalizedrecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normalized_records",
                to="api.organization",
            ),
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=50)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "uploaded_by",
                    models.CharField(default="System Analyst", max_length=100),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PROCESSING", max_length=50)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="api.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                ("raw_payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="api.ingestionbatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="normalizedrecord",
            name="raw_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normalized_records",
                to="api.rawrecord",
            ),
        ),
    ]
